### ISSUE TITLE
static files not loading

### ISSUE THREAD

**Issue by dac3971** [winzaa123/nuxt2-vuetify-ssr-on-firebase#1]
Hi, I got this to work but its just the unstyled html loading. Looks like the static assets (js, css) are returning a 404. Would really help me out if you had any suggestions!
Thanks

**Comment by winzaa123** [comment]
Can you try `yarn firebase:serve` test in local result found 404 same in firebase?, or `yarn build` before firebase:serve

**Comment by dac3971** [comment]
@winzaa123 tried those...no luck :(

**Comment by winzaa123** [comment]
@dac3971  in root directory you have public folder?

**Comment by winzaa123** [comment]
@dac3971  hey guy, Please try again , I re create and update to nuxt current version now :)

**Comment by dac3971** [comment]
@winzaa123 Tried again with the updated nuxt - still getting 404 on the static assets

**Comment by winzaa123** [comment]
for deploy (Firebase hosting)
1. `yarn build`
2. `yarn pre:public`   this step you run ok?
3. `yarn deploy`
